AllCops:
  Exclude:
    - 'bin/*'
    - 'gemfiles/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Lint/AssignmentInCondition:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - "spec/integration/**/*"

Metrics/AbcSize:
  Max: 29

Metrics/BlockLength:
  Max: 32
  ExcludedMethods:
    - describe

Metrics/ClassLength:
  Max: 198

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 34

Metrics/PerceivedComplexity:
  Max: 9

Naming/FileName:
  Exclude:
    - lib/resqued/quit-and-wait.rb

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    - before
    - each
    - it
    - kill_safely
    - let
    - new
    - watch
  FunctionalMethods:
    - trap

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    # TODO - add docs to these:
    - 'lib/resqued.rb'
    - 'lib/resqued/backoff.rb'
    - 'lib/resqued/config.rb'
    - 'lib/resqued/daemon.rb'
    - 'lib/resqued/listener_pool.rb'
    - 'lib/resqued/listener_state.rb'
    - 'lib/resqued/logging.rb'
    - 'lib/resqued/master_state.rb'
    - 'lib/resqued/procline_version.rb'
    - 'lib/resqued/quit-and-wait.rb'
    - 'lib/resqued/replace_master.rb'
    - 'lib/resqued/runtime_info.rb'
    - 'lib/resqued/sleepy.rb'
    - 'lib/resqued/test_case.rb'

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: sprintf

# maybe eventually, if positional tokens become difficult to maintain.
Style/FormatStringToken:
  Enabled: false

# TODO - figure out if frozen string literals will be ok.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Exclude:
    # Config specs need to pass data back and forth, and globals are the way to do it.
    # TODO - look into using a fixed name, to help avoid accidentally mistyping the var name.
    - 'spec/resqued/config_spec.rb'
    - 'spec/resqued/config/*'

Style/GuardClause:
  MinBodyLength: 4

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantBegin:
  # Ruby 3.0 changed some block syntax and 'begin' is sometimes optional now.
  # Leave this disabled until Resqued only supports Rubies where there's one
  # way to do it.
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RescueModifier:
  # TODO - enable this check and restructure the affected code.
  Enabled: false

Style/RescueStandardError:
  # TODO - enable this check and rescue the right types of things.
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
