#!/bin/bash
#/ Usage: script/ci [--ruby 3.0.0] [--gemfile gemfiles/GEMFILE]
#/ Run tests in a container, similar to one of the build matrix configurations.

set -e
set -o nounset

dcarg=
while [ $# -gt 0 ]; do
  case "$1" in
    --ruby)
      dcarg="$dcarg --build-arg RUBY_VERSION=$2"
      shift; shift;;
    --gemfile)
      dcarg="$dcarg --build-arg CI_GEMFILE=$2"
      shift; shift;;
    *)
      echo 'Usage: script/ci [--ruby VERSION] [--gemfile GEMFILE]'
      exit 1
      ;;
  esac
done

dc="docker-compose -f docker-compose.ci.yml"

$dc build --force-rm $dcarg
exec $dc run --rm test
