#!/bin/sh

test -d "/usr/share/rbenv/shims" && {
  export PATH=/usr/share/rbenv/shims:$PATH
}

for v in 1.9.3-p231-tcs-github 2.0.0-github
do
  export RBENV_VERSION=$v
  rbenv version
  ruby --version
  bundle --version
  ./script/bootstrap
  ./script/test
done
