#!/bin/sh

test -d "/usr/share/rbenv/shims" && {
  export PATH=/usr/share/rbenv/shims:$PATH
}

export RBENV_VERSION=1.9.3-p231-tcs-github
rbenv version
ruby --version
bundle --version
./script/bootstrap
./script/test
