#!/bin/sh
#/ Usage: script/release [--force] VERSION
#/ where VERSION looks like v0.7.13
#/ without --force, the release is previewed, but not applied.

set -e

usage() {
  cat "$0" | grep '^#/' | cut -c4-
}

dry_run=yes
version=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      dry_run=no
      ;;
    --*)
      usage
      exit 1
      ;;
    *)
      if [ "$#" -eq 1 ]; then
        version="$1"
      else
        usage 
        exit 1
      fi
  esac
  shift
done

## Validate the version number.

if [ -z "${version}" ]; then
  usage
  exit 1
fi

if ! echo "${version}" | grep -E '^v[0-9]+(\.[0-9]+)+' >/dev/null 2>/dev/null; then
  echo Error: "'${version}'" is not a valid version number.
  exit 2
fi

if git rev-parse --verify --quiet "refs/tags/${version}" >/dev/null; then
  echo Error: "'${version}'" already 'exists!'
  exit 3
fi

## Build the release

run() {
  echo "$@"
  if [ "${dry_run}" = "no" ]; then
    "$@"
  fi
}

run echo Releasing ${version}
