#!/bin/bash

CONFIG=tmp/test-all-resques-config.rb
OUTPUT=tmp/test-all-resques-output.txt
LOG=tmp/test-all-resques.log
PID=tmp/test-all-resques.pid

BUNDLE_INSTALL_ARGS="--path .bundle --binstubs"

mkdir -p tmp
rm -f $LOG

cat >$CONFIG <<END_CONFIG
before_fork do
  host = ENV['REDIS_HOST'] || 'localhost'
  port = ENV['REDIS_PORT'] || 6379
  Resque.redis = Redis.new(:host => host, :port => port)
end
after_fork do
  File.open('$OUTPUT', 'a') { |f| f.puts Gem.loaded_specs['resque'].version.to_s }
end
after_exit do |worker_summary|
  puts "#{worker_summary.alive_time_sec}"
end
worker 'example-queue'
END_CONFIG

try_version() {
  cat >Gemfile <<END_GEMFILE
source 'https://rubygems.org/'
gemspec
gem 'resque', '$resque_version'
END_GEMFILE
  rm -f Gemfile.lock
  if ! bundle install $BUNDLE_INSTALL_ARGS --local >&/dev/null
  then
    bundle install $BUNDLE_INSTALL_ARGS >&/dev/null
  fi

  ./bin/resqued -p $PID -l $LOG $CONFIG &
  sleep 10
  if [ -f $PID ]
  then
    kill -TERM `cat $PID`
    sleep 2
  fi
}

cp -f Gemfile tmp/test-all-resques-Gemfile.bak

# This list came from `gem list -r -a resque`
for resque_version in 1.24.1 1.24.0 1.23.1 1.23.0 1.22.0 1.21.0 1.20.0 1.19.0 1.18.6 1.18.5 1.18.4 1.18.3 1.18.2 1.18.1 1.18.0 1.17.1 1.17.0 1.16.1 1.16.0 1.15.0 1.14.0 1.13.0 1.12.0 1.11.0 1.10.0 1.9.10 1.9.9 1.9.8 1.9.7 1.9.5 1.9.4 1.9.3 1.9.2 1.9.1 1.9.0 1.8.6 1.8.5 1.8.4 1.8.3 1.8.2 1.8.1 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.2 1.5.1 1.5.0 1.4.0 1.3.1 1.3.0 1.2.3 1.2.1 1.2.0 1.1.0 1.0.0 0.2.0
do
  rm -f $OUTPUT
  try_version
  if [ -f $OUTPUT ]
  then
    if [ "`cat $OUTPUT`" = "$resque_version" ]
    then
      message="worked"
    else
      message="could not start worker"
    fi
  else
    message="did not run"
  fi
  echo $resque_version $message
done

cp -f tmp/test-all-resques-Gemfile.bak Gemfile
rm -f Gemfile.lock
bundle --local >&/dev/null
#pstree -s resqued
