#!/usr/bin/env ruby

if ARGV[0] == 'listener'
  require 'resqued/listener'
  Resqued::Listener.exec!
  exit 0
end

require 'optparse'

options = {}
daemonize = false
test = false

opts = OptionParser.new do |opts|
  opts.banner = "Usage: resqued [options] resqued-config-files..."

  opts.on '-h', '--help', 'Show this message' do
    puts opts
    exit
  end

  opts.on '-v', '--version', 'Show the version' do
    require 'resqued/version'
    puts Resqued::VERSION
    exit
  end

  opts.on '--test', 'Report which worker would start' do
    test = true
  end

  opts.on '--fast-exit', 'Exit quickly on SIGQUIT, SIGTERM' do
    options[:fast_exit] = true
  end

  opts.on '-p', '--pidfile PIDFILE', 'Store the pid of the master process in PIDFILE' do |v|
    options[:master_pidfile] = v
  end

  opts.on '-l', '--logfile LOGFILE', 'Write output to LOGFILE instead of stdout' do |v|
    require 'resqued/logging'
    Resqued::Logging.log_file = v
  end

  opts.on '-D', '--daemonize', 'Run daemonized in the background' do
    daemonize = true
  end

  opts.on '--exec-on-hup', 'Re-exec the master process on SIGHUP' do
    options[:exec_on_hup] = true
  end
end

opts.parse!
options[:config_paths] = ARGV

def require_config_paths!(options)
  if options[:config_paths].size == 0
    puts opts
    exit 1
  end
end

if test
  require_config_paths! options
  require 'resqued/config'
  workers = Resqued::Config.new(options[:config_paths]).build_workers
  puts "Workers defined in #{options[:config_paths].join(' ')}"
  workers.each_with_index do |worker, index|
    puts "#{index + 1}: #{worker.queues.join(',')}"
  end
else
  require_config_paths! options
  require 'resqued'
  Resqued.capture_start_ctx!
  state = Resqued::MasterState.new
  state.init(options)
  resqued = Resqued::Master.new(state)
  if daemonize
    require 'resqued/daemon'
    resqued = Resqued::Daemon.new(resqued)
  end
  resqued.run
end
